# Generated by Django 5.2 on 2025-04-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='thumbnail_file',
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail_url_override',
            field=models.URLField(blank=True, null=True),
        ),
    ]
