# Generated by Django 5.2 on 2025-04-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0002_media_site_media_thumbnail_url_media_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='embed_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
