# Generated by Django 5.2 on 2025-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0003_media_embed_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
