# Generated by Django 5.2 on 2025-04-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0004_alter_media_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='video_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
