# Generated by Django 5.2 on 2025-04-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0005_alter_media_video_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='media',
            name='title',
        ),
    ]
