# Generated by Django 5.2 on 2025-04-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0006_remove_media_thumbnail_url_remove_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
