# Generated by Django 5.2 on 2025-04-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0007_media_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='thumbnail_url',
        ),
    ]
