# Generated by Django 5.2 on 2025-04-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0008_remove_media_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='media',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
