# Generated by Django 5.2 on 2025-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0010_media_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('homepage_url', models.URLField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_development', 'Under Development')], default='active', max_length=20)),
            ],
        ),
    ]
