# Generated by Django 5.2 on 2025-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0011_platforminfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforminfo',
            name='nsfw',
            field=models.BooleanField(default=False),
        ),
    ]
