# Generated by Django 5.2 on 2025-04-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0013_platforminfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='platforminfo',
            name='user',
        ),
    ]
