# Generated by Django 5.2 on 2025-04-11 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0014_rename_author_media_user_remove_platforminfo_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.AddField(
            model_name='media',
            name='users',
            field=models.ManyToManyField(related_name='media', to=settings.AUTH_USER_MODEL),
        ),
    ]
