# Generated by Django 5.2 on 2025-04-11 12:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0015_remove_media_user_media_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='users',
            field=models.ManyToManyField(related_name='old_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GALLERY.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='user_media',
            field=models.ManyToManyField(related_name='media', through='GALLERY.UserMedia', to=settings.AUTH_USER_MODEL),
        ),
    ]
