# Generated by Django 5.2 on 2025-04-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0016_alter_media_users_usermedia_media_user_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='users',
        ),
    ]
