# Generated by Django 5.2 on 2025-04-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GALLERY', '0017_remove_media_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='user_media',
            new_name='users',
        ),
    ]
